[workspace]
resolver = "3"
members = ["sui", "sui_runner", "asset_provider" , "stage_manager", "stage_manager_tokio"]

[workspace.dependencies]
sui.path = "./sui"
sui_runner.path = "./sui_runner"
stage_manager.path = "./stage_manager"
stage_manager_tokio.path = "./stage_manager_tokio"

asset_provider.path = "./asset_provider"
asset_provider_image.path = "./asset_provider_image"

tokio = "1.46.1"

# see readme #usage
# this workspace definition is only used on github actions
