[workspace]
resolver = "3"
members = [
	"sui",
	"sui_runner",

	"asset_provider",
	"asset_provider_image",
	"asset_provider_font",

	"stage_manager",
	"stage_manager_loaders",
	"stage_manager_remote"
]

[workspace.dependencies]
sui.path = "./sui"
sui_runner.path = "./sui_runner"

asset_provider.path = "./asset_provider"
asset_provider_image.path = "./asset_provider_image"
asset_provider_font.path = "./asset_provider_font"

stage_manager.path = "./stage_manager"
stage_manager_loaders.path = "./stage_manager_loaders"
stage_manager_remote.path = "./stage_manager_remote"

tokio = "1.46.1"

# see readme #usage
# this workspace definition is only used on github actions
