[package]
name = "sui"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.9.0", default-features = false, features = ["std", "thread_rng"] }
rand_core = "0.9.0"
rand_pcg = "0.9.0"
raylib.workspace = true
